name: .NET

on:
  push:
    branches: [ development,main ]
  pull_request:
    branches: [ development ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore odh-imageresizer-core.sln
    - name: Build
      run: dotnet build odh-imageresizer-core.sln --no-restore
    - name: Test
      run: dotnet test odh-imageresizer-core.sln --no-build --verbosity normal
